import postgres from "postgres";
import dotenv from "dotenv";
dotenv.config();
const sql = postgres(process.env.DATABASE_URL, { ssl: { rejectUnauthorized: false }, prepare: false, idle_timeout: 5 });
const cols = await sql`SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'roster_players' ORDER BY ordinal_position`;
console.log("roster_players:", cols.map(c => c.column_name + ":" + c.data_type).join(", "));
const cols2 = await sql`SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'leagues' ORDER BY ordinal_position`;
console.log("leagues:", cols2.map(c => c.column_name + ":" + c.data_type).join(", "));
const cols3 = await sql`SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'players_master' ORDER BY ordinal_position`;
console.log("players_master:", cols3.map(c => c.column_name + ":" + c.data_type).join(", "));
const sample = await sql`SELECT * FROM roster_players LIMIT 2`;
console.log("sample rp:", JSON.stringify(sample));
await sql.end();
